In [22]:
import pandas as pd

df = pd.read_csv(r"C:\Users\User\Desktop\Pokemon\pokemon_data.csv.txt")
# print(df)
# print(df.head(5))

# Reading Pandas in Data

In [30]:
# Read Headers
(df.columns)
# Read each column
# print(df[["Name","Type 1","HP"]])
# Read each Row
# print(df.iloc[1:5])
# for index,row in df.iterrows():
#     print(index,row["Name"])
df.loc[df["Type 1"] == "Fire"]

# Read a specific location(R,C)
# print(df.iloc[2,1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# Sorting/Describing Data

In [34]:
df.sort_values(["Type 1", "HP"], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

# Making change to the Data

In [48]:
# df["Total"] = df["HP"] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]

# df = df.drop(columns=["Total"])
df["Total"] = df.iloc[:, 4:10].sum(axis=1)
cols = list(df.columns.values)
df =df[cols[0:4] + [cols[-1]] + cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,799.0,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,1015.0,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,1315.0,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,1595.0,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,747.0,39,52,43,60,50,65

In [86]:
# df.to_csv("modified.csv", index = False)
# df.to_excel("modified.xlsx", index =False)
df.to_csv("modified.txt", index =False, sep="\t")

df.head(5)

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,799.0,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,1015.0,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,1315.0,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,1595.0,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,747.0,39,52,43,60,50,65

# Filtern Data

In [112]:
# df.loc[(df["Type 1"] == "Grass") & (df["Type 2"] == "Poison") & (df["HP"] > 70)]
# new_df.to_csv("filtered.csv")
#  new_df.reset_index(drop =True, inplace=True)
#  new_df
import re

df.loc[df["Type 1"].str.contains("pi[a-z]", regex=True)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Generation, Legendary, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed]
Index: []

# Conditional Changes

In [120]:

 df= pd.read_csv(r"C:\Users\User\Desktop\modified.csv")
    
    
#  df.loc[df["Total"] > 500, ["Generation", "Legendary"]] = ["Test 1", "Test 2"]
#  df
# df.loc[df["Type 1"] == "Fire", "Legendary"] = "True"

# Aggregate statistics(Groupby)

In [124]:
df = pd.read_csv(r"C:\Users\User\Desktop\modified.csv")
df.groupby(["Type 1"]).mean().sort_values("Attack", ascending=False)

,Unnamed: 0,#,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,,,,
Dragon,521.843750,474.375000,3.875000,0.375000,1397.062500,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Fighting,400.444444,363.851852,3.370370,0.000000,1052.481481,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Ground,392.312500,356.281250,3.156250,0.125000,1122.062500,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Rock,431.840909,392.727273,3.454545,0.090909,1174.045455,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,486.296296,442.851852,3.851852,0.148148,1272.111111,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Dark,507.387097,461.354839,4.032258,0.064516,1115.451613,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Fire,360.942308,327.403846,3.211538,0.096154,1153.230769,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,746.500000,677.750000,5.500000,0.500000,1178.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Poison,278.285714,251.785714,2.535714,0.000000,1005.892857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Water,333.312500,303.089286,2.857143,0.035714,1088.955357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286
Ghost,536.281250,486.500000,4.187500,0.062500,1113.593750,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Normal,351.581633,319.173469,3.051020,0.020408,998.244898,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Grass,380.414286,344.871429,3.357143,0.042857,1069.185714,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ice,465.666667,423.541667,3.541667,0.083333,1097.250000,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Psychic,420.105263,380.807018,3.385965,0.245614,1178.824561,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Bug,368.072464,334.492754,3.217391,0.000000,948.623188,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Electric,400.590909,363.500000,3.272727,0.090909,1087.613636,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,494.529412,449.529412,4.117647,0.058824,1057.705882,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235